# Task 1


In [1]:
import numpy as np

In [2]:
np.random.seed(42)

A = np.random.randint(1, 101, 100)

print(A)


[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38   2  64  60  21  33  76  58  22  89  49  91  59  42  92  60  80
  15  62  62  47  62  51  55  64   3  51   7  21  73  39  18   4  89  60
  14   9  90  53   2  84  92  60  71  44   8  47  35  78  81  36  50   4
   2   6  54   4  54  93  63  18  90  44  34  74  62 100  14  95  48  15
  72  78  87  62  40  85  80  82  53  24]


In [3]:
print("Minimum:",np.min(A))
print("Maximum:",np.max(A))
print("Mean:",np.mean(A))
print("Median:",np.median(A))
print("Standard Deviation:",np.std(A))

Minimum: 2
Maximum: 100
Mean: 51.54
Median: 54.0
Standard Deviation: 29.278463074417004


In [4]:
B = np.arange(100)
print(B)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [6]:
zeros_array = np.zeros(5)
ones_array = np.ones(5)
print("Zeros array:",zeros_array)
print("Zeros shape:",zeros_array.shape)
print("Zeros data type:",zeros_array.dtype)

print("Ones array:",ones_array)
print("Ones shape:",ones_array.shape)
print("Ones data type:",ones_array.dtype)

Zeros array: [0. 0. 0. 0. 0.]
Zeros shape: (5,)
Zeros data type: float64
Ones array: [1. 1. 1. 1. 1.]
Ones shape: (5,)
Ones data type: float64


In [8]:
C = np.linspace(0,10,11)
print("Array C:",C)
print("Shape:", C.shape)
print("Data type:", C.dtype)


Array C: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Shape: (11,)
Data type: float64


np.arange() generates values based on a specified step size, whereas np.linspace() generates a specified number of evenly spaced values between a start and end point.

In [ ]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("2D Array:")
print(array_2d)

print("Shape:", array_2d.shape)
print("Number of dimensions:", array_2d.ndim)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2


In [10]:
print("Element at row 1, column 2:", array_2d[0, 1])

print("First element:", array_2d[0, 0])

print("Last element:", array_2d[-1, -1])

Element at row 1, column 2: 2
First element: 1
Last element: 9


In [11]:
print("First row:")
print(array_2d[0, :])

print("\nSecond row:")
print(array_2d[1, :])

print("\nFirst column:")
print(array_2d[:, 0])

print("\nSecond column:")
print(array_2d[:, 1])

First row:
[1 2 3]

Second row:
[4 5 6]

First column:
[1 4 7]

Second column:
[2 5 8]


In [12]:
print("First two rows:")
print(array_2d[0:2, :])

print("\nFirst two columns:")
print(array_2d[:, 0:2])

print("\nTop-left 2x2 section:")
print(array_2d[0:2, 0:2])

First two rows:
[[1 2 3]
 [4 5 6]]

First two columns:
[[1 2]
 [4 5]
 [7 8]]

Top-left 2x2 section:
[[1 2]
 [4 5]]


In [13]:
array_3d = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("3D Array:")
print(array_3d)

print("Shape:", array_3d.shape)
print("Number of dimensions:", array_3d.ndim)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Number of dimensions: 3


In [14]:
print("Element:", array_3d[0, 0, 1])

print("\nFirst block:")
print(array_3d[0])

print("\nSecond block:")
print(array_3d[1])

Element: 2

First block:
[[1 2]
 [3 4]]

Second block:
[[5 6]
 [7 8]]


In [15]:
print("First row from every block:")
print(array_3d[:, 0, :])

print("\nFirst column from every block:")
print(array_3d[:, :, 0])

First row from every block:
[[1 2]
 [5 6]]

First column from every block:
[[1 3]
 [5 7]]


In [16]:
print("First block:")
print(array_3d[0, :, :])

print("\nFirst row from every block:")
print(array_3d[:, 0, :])

print("\nFirst column from every block:")
print(array_3d[:, :, 0])

First block:
[[1 2]
 [3 4]]

First row from every block:
[[1 2]
 [5 6]]

First column from every block:
[[1 3]
 [5 7]]


In [17]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original matrix:")
print(matrix)

print("Original shape:", matrix.shape)

Original matrix:
[[1 2 3]
 [4 5 6]]
Original shape: (2, 3)


In [18]:
reshaped_matrix = matrix.reshape(3, 2)

print("Reshaped matrix:")
print(reshaped_matrix)

print("Reshaped shape:", reshaped_matrix.shape)

Reshaped matrix:
[[1 2]
 [3 4]
 [5 6]]
Reshaped shape: (3, 2)


In [19]:
flattened_array = reshaped_matrix.flatten()

print("Flattened array:")
print(flattened_array)

print("Flattened shape:", flattened_array.shape)

Flattened array:
[1 2 3 4 5 6]
Flattened shape: (6,)
